# Generated by Django 3.1.2 on 2023-02-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0006_ordersonpersonnel_op_dateofres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersonpersonnel',
            options={'ordering': ['-op_date'], 'verbose_name': 'Приказ по личному составу', 'verbose_name_plural': 'Приказы по личному составу'},
        ),
    ]
