# Generated by Django 4.1.1 on 2023-02-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TURV', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantionReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина отсутствия',
                'verbose_name_plural': 'Причины отсутствия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacantionShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='Период')),
                ('sup_check', models.BooleanField(default=False, verbose_name='Утвержден СУП')),
                ('res_officer', models.CharField(default='', max_length=256, verbose_name='Ответственный')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'График отпусков',
                'verbose_name_plural': 'Графики отпусков',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='VacantionShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacantionSheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_from', models.DateField(verbose_name='Период с')),
                ('dur_to', models.DateField(verbose_name='Период по')),
                ('move_from', models.DateField(blank=True, null=True, verbose_name='Перенос с: ')),
                ('move_to', models.DateField(blank=True, null=True, verbose_name='перенос по: ')),
                ('move_reason', models.TextField(default='', help_text='Введите основание переноса', verbose_name='Основание переноса')),
                ('child_year', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Год рож-я иждивенца: ')),
                ('city', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Проезд: ')),
                ('days_count', models.IntegerField(verbose_name='Количество дней')),
                ('days_count_move', models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней после переноса ')),
                ('comm', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('bound_shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vac_shed.vacantionshedule')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.employers', verbose_name='Сотрудник')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vac_shed.vacantionreasons', verbose_name='Причина отсутствия')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vac_shed.vacantionshifts', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Элемент графика',
                'verbose_name_plural': 'Элементы графика',
                'ordering': ['-bound_shed__year'],
            },
        ),
    ]
