# Generated by Django 4.1.1 on 2023-02-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantionsheduleitem',
            name='shift',
        ),
    ]
