# Generated by Django 4.1.1 on 2023-02-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0002_remove_vacantionsheduleitem_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vac_shed.vacantionshifts', verbose_name='Смена'),
        ),
    ]
